version: '3'
services:
  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
    - rails-app
    - db
    
  content-api:
    build:
      context: content-api
      dockerfile: Dockerfile
    env_file:
      - .env

  rails-app:
    build:
      context: rails-app
      dockerfile: Dockerfile
    env_file:
      - .env
    command: /app/start.sh
    ports:
      - 3000:3000

volumes:
  postgres_data:
